export default () => (
  <g id="eyes04" stroke="none" strokeWidth="1" fill="none">
    <circle
      id="Oval"
      stroke="#333333"
      strokeWidth="4"
      fill="#FFFFFF"
      cx="27"
      cy="20"
      r="13"
    ></circle>
    <circle
      id="Oval"
      stroke="#333333"
      strokeWidth="4"
      fill="#FFFFFF"
      cx="72"
      cy="20"
      r="13"
    ></circle>
    <circle
      id="Oval"
      stroke="#333333"
      strokeWidth="4"
      fill="#333333"
      cx="30"
      cy="19"
      r="8"
    ></circle>
    <circle
      id="Oval"
      stroke="#FFFFFF"
      strokeWidth="2"
      fill="#FFFFFF"
      cx="34"
      cy="15"
      r="2"
    ></circle>
    <circle
      id="Oval"
      stroke="#333333"
      strokeWidth="4"
      fill="#333333"
      cx="75"
      cy="19"
      r="8"
    ></circle>
    <circle
      id="Oval"
      stroke="#FFFFFF"
      strokeWidth="2"
      fill="#FFFFFF"
      cx="79"
      cy="15"
      r="2"
    ></circle>
  </g>
);
